### PR TITLE
Added new command line parameter 'secure-error-report-valve'

### PR DESCRIPTION
**Pull request by chrisupb**
There are special malicious request for which Tomcat usually logs stacktraces to the caller. Try a Null Code attack like https://XX.herokuapp.com/application/anything%00 . Tomcat will always answer it using the properties in the ErrorReportValve.

These requests aren't even dispatched to the deployed applications and thus error pages don't solve the problem.
This pull requests adds a new option to set the properties showReport and showServerInfo of ErrorReportValve to false.

Please also merge into tomcat9 branch

See https://help.heroku.com/tickets/1027939

### CODE REVIEW

**Review by Malax — APPROVED** [review]
Thank you for your contribution! 👍🏻

**Comment by Malax** [comment]
@chrisupb I just ran CI for this and it seems like you need to run a quick `./mvnw spotless:apply` and commit the formatting changes before we can merge and ship this. :)

**Comment by chrisupb** [comment]
Done!

**Comment by Malax** [comment]
Thanks again @chrisupb! I merged this and cut a release so you can start using this immediately. The first version with the changes from this PR is `9.0.69.1`. It might take a couple of minutes before it appears on Maven central.

**Pull request merged**
