### PR TITLE
Update Tomcat 8.5 to latest patch release 8.5.68

### PR DESCRIPTION
**Pull request by schneems**
Sub pom.xml files need to be updated in addition to the top level https://github.com/heroku/webapp-runner/pull/224.

### CODE REVIEW

**Review by Malax — APPROVED** [review]

**Review by Malax — APPROVED** [review]

**Comment by Malax** [comment]
Thanks for improving the output when the tests fail! :)

**Review by edmorley — COMMENTED** [review]
Dependabot supports specifying custom directories - I think we might be able to add multiple entries to the dependabot config to cover both the repo root and these subdirectories, that way we don't need to manually update them:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#directory

I wonder if it's worth not updating the version in this PR, just so we can check the above approach works when Dependabot opens the PRs for us?

**Comment by Malax** [comment]
@edmorley:
> that way we don't need to manually update them

There is a slight problem with that approach. By convention, `webapp-runner`'s version is always the version of the Tomcat dependency. Dependabot would not do that change for us. I agree that it's worthwhile having dependabot notify us of Tomcat updates, but we'd still need to do some manual work.

> I wonder if it's worth not updating the version in this PR, just so we can check the above approach works when Dependabot opens the PRs for us?

Just for trying if it works with multiple branches? Yeah, why not.

**Comment by edmorley** [comment]
> By convention, `webapp-runner`'s version is always the version of the Tomcat dependency.

Ah I didn't know this.

> I mentioned to @schneems that a CI check that checks for this convention would be great.

+1

**Comment by Malax** [comment]
Tracking the CI check as GUS-W-9802671.

**Pull request merged**
