### PR TITLE
Added new command line parameter 'secure-error-report-valve'

### PR DESCRIPTION
**Pull request by chrisupb**
There are special malicious request for which Tomcat usually logs stacktraces to the caller. Try a Null Code attack like https://XX.herokuapp.com/application/anything%00 . Tomcat will always answer it using the properties in the ErrorReportValve.

These requests aren't even dispatched to the deployed applications and thus error pages don't solve the problem.
This pull requests adds a new option to set the properties showReport and showServerInfo of ErrorReportValve to false.

Please also merge into tomcat9 branch

See https://help.heroku.com/tickets/1027939

### CODE REVIEW

**Review by edmorley — COMMENTED** [review]
(I'm about to enable review reminder for team-alias reviews, so I'm switching any reviews that need language-owner review to the owner directly, to prevent reminders the rest of the team can't action)

**Comment by chrisupb** [comment]
Any progress here? :)

**Comment by Malax** [comment]
Hey @chrisupb! Sorry for the continued delays on your PR. I did some broad stroke changes in this repo and your PR doesn't apply cleanly anymore. Would you mind rebasing so we can finally tackle this? :)

Again, sorry for the delay!

**Comment by chrisupb** [comment]
I'll do this one again.

**Pull request closed without merging**
